import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { GridProvider } from "./lib/gridProvider";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GridProvider>{children}</GridProvider>
      </body>
    </html>
  );
}
