import localFont from "next/font/local";

const switzer = localFont({
  src: "../public/fonts/Switzer-Variable.woff2",
});

import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { Providers } from "./lib/providers";
import Nav from "./ui/navigation/nav";
import Footer from "./ui/footer";
const inter = Inter_Tight({ subsets: ["latin"], display: "swap" });
import Cursor from "./ui/cursor";

import { getNavigation } from "@/app/lib/getNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const nav = await getNavigation();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers attribute="class">
          <Cursor />
          <Nav nav={nav}/>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
